name: hasty
description: A SwiftUI-inspired static site generator for Dart. Build HTML with HStacks, VStacks, and zero CSS stress.
version: 0.0.1
repository: https://github.com/BendyLand/Hasty

environment:
  sdk: ^3.10.7

dependencies:
  mason_logger: ^0.3.3
  beautiful_soup_dart: ^0.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
